# Site settings
title: "Ewerthon’s Projects"
description: "A collection of my personal projects and updates"
author: "Ewerthon Melzani"
baseurl: "" # leave empty for personal site repo
url: "https://ewerthonmelzani.github.io"


remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache

# load extra CSS (we’ll create this file next)
custom_css:
  - /assets/css/custom.css


# Navigation menu
navigation:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "CV"
    url: /cv/
  - title: "Contact"
    url: /contact/


# Social links (these WILL display on homepage if you add them in index.md)
social_links:
  github: "https://github.com/ewerthonmelzani"
  linkedin: "https://linkedin.com/in/YOUR-LINK"
  twitter: "https://twitter.com/YOUR-LINK"
