# Site settings
title: "Ewerthon’s Projects"
description: "A collection of my personal projects and updates"
author: "Ewerthon Melzani"
baseurl: "" # leave empty for personal repo
url: "https://ewerthonmelzani.github.io"

# Built-in GitHub Pages theme
theme: jekyll-theme-cayman

# Navigation (Cayman does not automatically use this; we'll add manually in pages)
navigation:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/
  - title: "CV"
    url: /cv/
  - title: "Contact"
    url: /contact/
  - title: "About"
    url: /about/

# Social links (for reference)
social_links:
  github: "https://github.com/ewerthonmelzani"
  linkedin: "https://www.linkedin.com/in/ewerthon-melzani-22b085298/"
  email: "mailto:ervithon@gmail.com"
