title: Ewerthon Melzani
description: "Personal website using Tor Navigator-inspired style"
baseurl: "" # user GitHub Pages site
url: "https://EwerthonMelzani.github.io"
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag




# Social links (for reference)
social_links:
  github: "https://github.com/ewerthonmelzani"
  linkedin: "https://www.linkedin.com/in/ewerthon-melzani-22b085298/"
  email: "mailto:ervithon@gmail.com"
